base:
  random_state: 42
  log_file: mylog.log

data_load:
  dataset_csv: data/raw/diabetes.csv

data_clean:
  test_size: 0.2
  X_train: data/processed/X_train.csv
  y_train: data/processed/y_train.csv
  X_test: data/processed/X_test.csv
  y_test: data/processed/y_test.csv

train:
  model_file: models/rf_model.pkl

evaluate:
  metrics_file: results/evaluation_metrics.yaml
  scatter_plot_file: results/scatter_plot.png
  line_plot_file: results/line_plot.png