stages:

  load_data:
    cmd: python src/scripts/data_load.py --config config.yaml
    deps:
      - config.yaml
    outs:
      - data/raw/diabetes.csv

  clean_data:
    cmd: python src/scripts/data_clean.py --config config.yaml
    deps:
      - config.yaml
      - data/raw/diabetes.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_model:
    cmd: python src/scripts/train.py --config config.yaml
    deps:
      - config.yaml
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/rf_model.pkl

  evaluate_model:
    cmd: python src/scripts/evaluate.py --config config.yaml
    deps:
      - config.yaml
      - models/rf_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    metrics:
      - results/evaluation_metrics.yaml
    outs:
      - results/line_plot.png
      - results/scatter_plot.png