stages:

  load_data:
    cmd: python src/scripts/data_load.py --config configs.yaml
    outs:
      - data/raw/diabetes.csv

  clean_data:
    cmd: python src/scripts/data_clean.py --config configs.yaml
    deps:
      - data/raw/diabetes.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_model:
    cmd: python src/scripts/train.py --config configs.yaml --params params.yaml
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    params:
      - train.n_estimators
      - train.max_depth
    outs:
      - models/rf_model.pkl

  evaluate_model:
    cmd: python src/scripts/evaluate.py --config configs.yaml
    deps:
      - models/rf_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    metrics:
      - results/evaluation_metrics.yaml:
          cache: false
    outs:
      - results/line_plot.png:
          cache: false
      - results/scatter_plot.png:
          cache: false